version: "3.7"
services:
  app:
    image: test:wemake-services
    working_dir: /usr/code
    build:
      context: .
    volumes:
      - ./:/usr/code
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=some_key
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=test_assignment.settings.dev
    command: python manage.py runserver 0.0.0.0:5000
